### PR TITLE
Thunderbird 128.3.3esr

### PR DESCRIPTION
**Pull request by leviport**
* https://www.thunderbird.net/en-US/thunderbird/128.3.3esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/7791b5d54344169bb5e9c35f93868b18e40a4b5f

### CODE REVIEW

**Comment by jacobgkau** [comment]
You beat me by a few seconds. FYI, I found https://hg.mozilla.org/releases/comm-esr128/ with the commit log for this channel of Thunderbird (this release is https://hg.mozilla.org/releases/comm-esr128/log/7791b5d54344169bb5e9c35f93868b18e40a4b5f).

Also, you can cherry-pick 1bf4179bb037eb60d598d881b049397ece61e070 from my branch to make `update.sh` executable, if you'd like.

**Comment by leviport** [comment]
Ah will do, thanks!

**Comment by leviport** [comment]
Updated with the mercurial link and cherry-picked your commit.

**Review by mmstick — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Thunderbird's still working, theming and launcher behavior have not changed.

**Pull request merged**
